import mongoose from "mongoose"

const GameSchema = mongoose.Schema({
  board: [
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
    [
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
      { kind: { type: String }, color: { type: String } },
    ],
  ],
  canCastle: {
    White: {
      leftRook: { type: Boolean },
      king: { type: Boolean },
      rightRook: { type: Boolean },
    },
    Black: {
      leftRook: { type: Boolean },
      king: { type: Boolean },
      rightRook: { type: Boolean },
    },
  },
  turn: { type: String },
  result: { type: String },
})

export const Game = mongoose.model("game", GameSchema)
